### ISSUE TITLE
Deserialization error when retrieving ASG info from clouddriver

### ISSUE THREAD

**Issue by lorin** [spinnaker/keel#1067]
We're getting the following error for one app, in prestaging:

```
MissingKotlinParameterException:Instantiation of
[simple type, class com.netflix.spinnaker.keel.clouddriver.model.ActiveServerGroup]
value failed for JSON property image due to missing (therefore NULL) value for creator 
parameter image which is a non-nullable type
```

<details><summary>complete stack trace</summary>

```
com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class com.netflix.spinnaker.keel.clouddriver.model.ActiveServerGroup] value failed for JSON property image due to missing (therefore NULL) value for creator parameter image which is a non-nullable type
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 6493] (through reference chain: com.netflix.spinnaker.keel.clouddriver.model.ActiveServerGroup["image"])
  at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:112)
  at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:198)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
  at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1719)
  at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1244)
  at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
  at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
  at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:227)
  at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:142)
  at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)

com.netflix.spinnaker.keel.plugin.CannotResolveCurrentState: Unable to resolve current state of ec2:cluster:test:keeldemo-test due to: Instantiation of [simple type, class com.netflix.spinnaker.keel.clouddriver.model.ActiveServerGroup] value failed for JSON property image due to missing (therefore NULL) value for creator parameter image which is a non-nullable type
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 6493] (through reference chain: com.netflix.spinnaker.keel.clouddriver.model.ActiveServerGroup["image"])
  at com.netflix.spinnaker.keel.actuation.ResourceActuator$resolve$2$current$1.invokeSuspend(ResourceActuator.kt:209)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
  at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

</details>

**Comment by lorin** [comment]
This looks like a clouddriver issue.

**Comment by lorin** [comment]
Fixed by https://github.com/spinnaker/clouddriver/pull/4545.
