### ISSUE TITLE
Instances stuck with high CPU utilization

### ISSUE THREAD

**Issue by lorin** [spinnaker/keel#1141]
We saw two out of four instances stop making resource checks, both report very high CPU utilization:

<details>
<summary>CPU graph</summary>

![image](https://user-images.githubusercontent.com/446305/81355319-078cb980-9083-11ea-9e78-9b6aa712891a.png)
</details>

Flame graph ([flamegraph.zip](https://github.com/spinnaker/keel/files/4596343/flamegraph.zip)) shows the stuck instances spending their time in ConcurrentHashMap code:

![image](https://user-images.githubusercontent.com/446305/81355520-a2859380-9083-11ea-8920-a65fb6dcb5ed.png)

[Complete thread dump gist](https://gist.github.com/lorin/e9919ca28e7a521168acfc49e668450f), relevant stack trace below:

<details>
<summary>relevant thread dump</summary>

```
"https-jsse-nio-7002-exec-9 @coroutine#66311" #68 daemon prio=5 os_prio=0 tid=0x00007efdd29d5000 nid=0x119d runnable [0x00007efd79958000]
   java.lang.Thread.State: RUNNABLE
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1934)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2377)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2360)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache.getOrNotFound(MemoryCloudDriverCache.kt:136)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache.securityGroupById(MemoryCloudDriverCache.kt:71)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.getSecurityGroupNames(ClusterHandler.kt:965)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.toServerGroup(ClusterHandler.kt:855)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.access$toServerGroup(ClusterHandler.kt:85)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler$getServerGroups$5$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(ClusterHandler.kt:808)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache$getOrNotFound$1.apply(MemoryCloudDriverCache.kt:138)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache$getOrNotFound$1.apply(MemoryCloudDriverCache.kt:31)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2379)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$947/1743548301.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	- locked <0x0000000731962820> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2377)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2360)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache.getOrNotFound(MemoryCloudDriverCache.kt:136)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache.securityGroupById(MemoryCloudDriverCache.kt:71)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.getSecurityGroupNames(ClusterHandler.kt:965)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.toServerGroup(ClusterHandler.kt:855)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.access$toServerGroup(ClusterHandler.kt:85)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler$getServerGroups$5$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(ClusterHandler.kt:808)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache$getOrNotFound$1.apply(MemoryCloudDriverCache.kt:138)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache$getOrNotFound$1.apply(MemoryCloudDriverCache.kt:31)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2379)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$947/1743548301.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	- locked <0x00000007319627c0> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2377)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2360)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache.getOrNotFound(MemoryCloudDriverCache.kt:136)
	at com.netflix.spinnaker.keel.clouddriver.MemoryCloudDriverCache.securityGroupById(MemoryCloudDriverCache.kt:71)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.getSecurityGroupNames(ClusterHandler.kt:965)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.toServerGroup(ClusterHandler.kt:855)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler.access$toServerGroup(ClusterHandler.kt:85)
	at com.netflix.spinnaker.keel.ec2.resource.ClusterHandler$getServerGroups$5$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(ClusterHandler.kt:808)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.netflix.spinnaker.keel.rest.ExportController.get(ExportController.kt:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at com.netflix.spinnaker.fiat.shared.FiatAuthenticationFilter.doFilter(FiatAuthenticationFilter.java:65)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.netflix.spinnaker.platform.netflix.security.auth.MetatronAuthenticationFilter.doFilter(MetatronAuthenticationFilter.java:118)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at javax.servlet.FilterChain$doFilter$1.call(Unknown Source)
	at com.netflix.spinnaker.filters.AuthenticatedRequestFilter.doFilter(AuthenticatedRequestFilter.groovy:143)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	- locked <0x000000072a8c7368> (a org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- <0x00000006d2f129f0> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

</details>

**Comment by ben-manes** [comment]
Recursive computations are not supported by ConcurrentHashMap. In Java 8 it live locks, and fails in later versions. That looks to be the problem here.

**Comment by lorin** [comment]
@ben-manes Thanks for that insight. I think the problem is in the [getOrNotFound][1] method in our codebase, and how it interacts with kotlin coroutines.

The `getOrNotFound` method calls `LocalManualCache.get`, passing a mappingFunction to compute the value on cache miss.

When there's a cache miss, the mappingFunction we pass ultimately calls the `ConcurrentHashMap.compute` method, which makes a call to [runBlocking][2] from inside of that method.

Once that call is made, control is yielded back to the kotlin coroutine scheduler (still inside of the `compute` method!).  If we get unlucky and the new coroutine ends up calling `getOrNotFound` on the same Cache object, then we end up with an unsupported recursive `ConcurrentHashMap.compute` call.

The upshot is that **it's not safe to call suspending kotlin functions from within the second argument to the [Cache.get method][3],** because this may result in a recursive call to `ConcurrentHashMap.compute`.

cc @robfletcher 

[1]: https://github.com/spinnaker/keel/blob/949b22245e268c12f15cbbedfcbc1f82de2c0aa7/keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt#L132-L147

[2]: https://github.com/spinnaker/keel/blob/949b22245e268c12f15cbbedfcbc1f82de2c0aa7/keel-clouddriver/src/main/kotlin/com/netflix/spinnaker/keel/clouddriver/MemoryCloudDriverCache.kt#L138

[3]: https://javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/index.html

**Comment by ben-manes** [comment]
Would using an `AsyncCache` make sense to use with coroutines? That performs a computation only long enough to create the `CompletableFuture`, letting its computation be performed outside of the map. Kotlin supports converting between future and coroutine, so I'd imagine it would play better?

**Comment by lorin** [comment]
Yeah, it looks like the [kotlinx-coroutines-jdk8](https://github.com/Kotlin/kotlinx.coroutines/tree/master/integration/kotlinx-coroutines-jdk8) module has some integration logic. I'll look at using `AsyncCache` here.
