### ISSUE TITLE
Security groups with "all protocols" and/or "all ports" are handled incorrectly

### ISSUE THREAD

**Issue by lorin** [spinnaker/keel#1290]
Keel errors when trying to process a security group from clouddriver that indicates "all protocols" or "all port ranges".

Clouddriver encodes all protocols as `"-1"` and "all ports" as a list with an empty map, like this:

```json
"inboundRules": [
        {
            "class": "com.netflix.spinnaker.clouddriver.model.securitygroups.IpRangeRule",
            "range": {
                "ip": "192.0.2.0",
                "cidr": "/24"
            },
            "protocol": "-1",
            "portRanges": [
                {}
            ],
            "description": "description goes here"
        }
    ]

```

Abbreviated stack trace:

```
java.lang.IllegalArgumentException: No enum constant com.netflix.spinnaker.keel.api.ec2.SecurityGroupRule.Protocol.-1
  at java.lang.Enum.valueOf(Enum.java:238)
  at com.netflix.spinnaker.keel.api.ec2.SecurityGroupRule$Protocol.valueOf(SecurityGroupRule.kt:-1)
  at com.netflix.spinnaker.keel.ec2.resource.SecurityGroupHandler.toSecurityGroup(SecurityGroupHandler.kt:274)
  at com.netflix.spinnaker.keel.ec2.resource.SecurityGroupHandler.access$toSecurityGroup(SecurityGroupHandler.kt:54)
```

**Comment by lorin** [comment]
Fix in PR #1293
