### ISSUE TITLE
Rethink repository structure in code

### ISSUE THREAD

**Issue by emjburns** [spinnaker/keel#740]
We currently have three main repositories (artifact, resource, and delivery config). These grew organically as we added delivery configs. Now that we no longer support resources w/o delivery configs we should reconsider how things are structured. Since you can never have a resource without a delivery config you shouldn't have to wire in both and do the orchestration yourself in various places.

I propose constructing a general repository that contains the existing repositories and orchestrates saving, updating, and deleting. This is mostly a kotlin-level change in how we interact with the storage layer in `keel`.

**Comment by luispollo** [comment]
Would this also involve removing the `ResourcePersister` and `Cleaner` classes?

**Comment by emjburns** [comment]
🤷‍♀ yes probably.

**Comment by luispollo** [comment]
As requested, reporting a SQL-related error that we might be able to solve as part of this refactoring:
```
com.netflix.spinnaker.keel.plugin.CannotResolveDesiredState: Unable to resolve desired state of titus:cluster:titustestvpc:mddemotitus due to: Cursor returned more than one result
   at com.netflix.spinnaker.keel.actuation.ResourceActuator$resolve$2$desired$1.invokeSuspend(ResourceActuator.kt:130)
   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
Caused by: org.jooq.exception.TooManyRowsException: Cursor returned more than one result
   at org.jooq_3.12.3.MYSQL.debug(Unknown Source)
   at org.jooq.impl.Tools.fetchOne(Tools.java:2087)
   at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:653)
   at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:658)
   at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2892)
   at com.netflix.spinnaker.keel.sql.SqlDeliveryConfigRepository$deliveryConfigFor$1.invoke(SqlDeliveryConfigRepository.kt:343)
   at com.netflix.spinnaker.keel.sql.SqlDeliveryConfigRepository$deliveryConfigFor$1.invoke(SqlDeliveryConfigRepository.kt:44)
   at com.netflix.spinnaker.keel.sql.SqlRetry$sam$java_util_function_Supplier$0.get(SqlRetry.kt)
   at io.github.resilience4j.retry.Retry.lambda$decorateSupplier$2(Retry.java:177)
   at io.vavr.control.Try.of(Try.java:75)
   at io.vavr.control.Try.ofSupplier(Try.java:92)
   at com.netflix.spinnaker.keel.sql.SqlRetry.withRetry(SqlRetry.kt:35)
   at com.netflix.spinnaker.keel.sql.SqlDeliveryConfigRepository.deliveryConfigFor(SqlDeliveryConfigRepository.kt:335)
   at com.netflix.spinnaker.keel.docker.DockerImageResolver.invoke(DockerImageResolver.kt:75)
   at com.netflix.spinnaker.keel.docker.DockerImageResolver.invoke(DockerImageResolver.kt:40)
   at com.netflix.spinnaker.keel.plugin.ResourceHandler.applyResolvers(ResourceHandler.kt:67)
   at com.netflix.spinnaker.keel.plugin.ResourceHandler.desired(ResourceHandler.kt:79)
   at com.netflix.spinnaker.keel.actuation.ResourceActuator.desired(ResourceActuator.kt:168)
   at com.netflix.spinnaker.keel.actuation.ResourceActuator$resolve$2$desired$1.invokeSuspend(ResourceActuator.kt:126)
```

This seems to have been caused by declaring two titus cluster resources in different environments in a delivery config which both had the same moniker. This ended up generating two records with the same resource id in the `environment_resource` table.
