### ISSUE TITLE
Unhappy veto throwing DateTimeParseException

### ISSUE THREAD

**Issue by lorin** [spinnaker/keel#894]
Seeing the following exception:

```
java.time.format.DateTimeParseException: Text cannot be parsed to a Duration
	at java.time.Duration.parse(Duration.java:412)
	at com.netflix.spinnaker.keel.veto.unhappy.UnhappyVeto.getWaitingTime(UnhappyVeto.kt:117)
	at com.netflix.spinnaker.keel.veto.unhappy.UnhappyVeto.waitingTime(UnhappyVeto.kt:112)
	at com.netflix.spinnaker.keel.veto.unhappy.UnhappyVeto.check(UnhappyVeto.kt:69)
	at com.netflix.spinnaker.keel.veto.VetoEnforcer.canCheck(VetoEnforcer.kt:37)
	at com.netflix.spinnaker.keel.actuation.ResourceActuator$checkResource$2.invokeSuspend(ResourceActuator.kt:79)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

See #866 for additional logging to help debug this issue.

**Comment by luispollo** [comment]
@lorin Was there anything remaining to close #894?

**Comment by lorin** [comment]
@luispollo I believe this (really #866) will just improve the logging to help us debug what's going wrong, rather than an actual fix, so this should remain open until we've figured out the nature of hte failure mode.

**Comment by lorin** [comment]
It appears that #895 resolved this after all. It may be that setting the default value in the annotation fixed the issue.
