### ISSUE TITLE
Titus image resolver throwing errors

### ISSUE THREAD

**Issue by lorin** [spinnaker/keel#900]
Seeing the following exception:

```
com.netflix.spinnaker.keel.plugin.CannotResolveDesiredState: Unable to resolve desired state of titus:cluster:titustestvpc:crossfireoptimizationworker due to: List is empty.
	at com.netflix.spinnaker.keel.actuation.ResourceActuator$resolve$2$desired$1.invokeSuspend(ResourceActuator.kt:177)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
Caused by: java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:206)
	at com.netflix.spinnaker.keel.api.titus.cluster.TitusImageResolver$getDigest$1.invokeSuspend(TitusImageResolver.kt:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:271)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.netflix.spinnaker.keel.api.titus.cluster.TitusImageResolver.getDigest(TitusImageResolver.kt:71)
	at com.netflix.spinnaker.keel.docker.DockerImageResolver.getContainer(DockerImageResolver.kt:122)
	at com.netflix.spinnaker.keel.docker.DockerImageResolver.invoke(DockerImageResolver.kt:84)
	at com.netflix.spinnaker.keel.docker.DockerImageResolver.invoke(DockerImageResolver.kt:39)
	at com.netflix.spinnaker.keel.api.plugins.ResourceHandler.applyResolvers(ResourceHandler.kt:43)
	at com.netflix.spinnaker.keel.api.plugins.ResourceHandler.desired(ResourceHandler.kt:55)
	at com.netflix.spinnaker.keel.actuation.ResourceActuator.desired(ResourceActuator.kt:217)
	at com.netflix.spinnaker.keel.actuation.ResourceActuator$resolve$2$desired$1.invokeSuspend(ResourceActuator.kt:173)
```

Currently being addressed in #897.

**Comment by emjburns** [comment]
Fixed!
