### ISSUE TITLE
Delivery config validation allows bad depends-on environment references

### ISSUE THREAD

**Issue by luispollo** [spinnaker/keel#936]
Given a delivery config like this:
```yaml
name: myapp
application: myapp
serviceAccount: delivery-engineering@netflix.com
artifacts:
   # ...
environments:
  - name: envA
    constraints: []
    notifications: []
    resources:
      - kind: "titus/cluster@v1"
        metadata: {}
        spec:
          moniker:
            app: myapp
            stack: envA
  - name: envB
    constraints:
      - type: depends-on
        environment: badEnvReference
    notifications: []
    resources:
      - kind: "titus/cluster@v1"
        metadata: {}
        spec:
          moniker:
            app: myapp
            stack: envB
```

Keel is allowing the file to be submitted and then blowing up with this exception:
```
java.lang.IllegalArgumentException: No environment named test exists in the configuration mddemotitus
   at com.netflix.spinnaker.keel.constraints.DependsOnConstraintEvaluator.canPromote(DependsOnConstraintEvaluator.kt:31)
   at com.netflix.spinnaker.keel.actuation.EnvironmentPromotionChecker.checkConstraints(EnvironmentPromotionChecker.kt:247)
   at com.netflix.spinnaker.keel.actuation.EnvironmentPromotionChecker.checkStatelessConstraints(EnvironmentPromotionChecker.kt:198)
   at com.netflix.spinnaker.keel.actuation.EnvironmentPromotionChecker.checkEnvironments$suspendImpl(EnvironmentPromotionChecker.kt:101)
   at com.netflix.spinnaker.keel.actuation.EnvironmentPromotionChecker.checkEnvironments(EnvironmentPromotionChecker.kt)
   at com.netflix.spinnaker.keel.actuation.CheckScheduler$checkEnvironments$job$1$invokeSuspend$$inlined$forEach$lambda$1$1.invokeSuspend(CheckScheduler.kt:106)
   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665
```

**Comment by gal-yardeni** [comment]
Worth addressing this bug with returning more meaningful error messages when submitting a delivery config.

**Comment by luispollo** [comment]
@gal-yardeni I'm planning to address #367 soon. We can divide and conquer here: you can address this issue by adding a new check to `CombinedRepository.validate(config: DeliveryConfig)`, and I'll work on making sure `ValidationException` returns error information that the UI can parse from `ExceptionHandler`. How does that sound?

**Comment by gal-yardeni** [comment]
I'm confused -- I thought https://github.com/spinnaker/keel/issues/367 is done but I see it's reopened :) 
I think it makes sense - I won't start working on until probably Friday, so we can sync then and catch up if needed.
